name: OutpostRankPerks
main: me.bxoxb.rankinfo.Main
version: "1.3"
author: Bxoxb
description: Display Rank Perks
commands:
  savage:
    description: Shows Rank info for savage
    usage: /savage
  brawler:
    description: Shows Rank info for brawler
    usage: /brawler
  mercenary:
    description: Shows Rank info for mercenary
    usage: /mercenary
  fighter:
    description: Shows Rank info for fighter
    usage: /fighter
  gladiator:
    description: Shows Rank info for gladiator
    usage: /gladiator